<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <MSBuildEnableWorkloadResolver Condition="'$(MSBuildEnableWorkloadResolver)' == ''">false</MSBuildEnableWorkloadResolver>
  </PropertyGroup>
</Project>
