global using Avalonia;
global using Avalonia.Controls;
global using SlickWatch.Core;
global using System;
global using System.IO;
global using System.Linq;
global using System.Collections.Generic;
global using System.Threading;
global using System.Threading.Tasks;
